name: Delete Workflow Runs

#on: [push]

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete Workflow Runs
        uses: leezhiming98/delete-workflow-runs@v1.9
        with:
          token: ${{ github.token }}
          owner: leezhiming98
          repo: github-actions
          branch_type: all
          retain_days: 120
###
# branch_type - protected|unprotected|all
# call the workflow once, if all branches having the same retain days
# eg. all - 30 days
# call the workflow twice, if protected and unprotected branches having different retain days
# eg. protected - 30 days | unprotected - 7 days
###
