name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    branches: [main]
    types: [merged]
jobs:
  check-bats-version:
    #if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo "🎉 ${{ github.base_ref }}"
      - if: ${{ github.base_ref == 'main' }}
        run: echo "Main Condition"
      - if: ${{ github.base_ref == 'demo' }}
        run: echo "Demo Condition"
